# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1896bed076739aec956a015d413e54180782aa211e4080f8e719d6e50e7e90577cefc071d5edd3b0599ee18668cca5c7f2c61132265de25d3900d81e5d2ea211

test:
  secret_key_base: b91ac106bfa8eb1e5e7483aca5bb201a239712dd793fec7c293b595d150f0044fc8ef83e30e0c3d24ec3b5230577ba70f20a54fa0a2e5edc027715df2b332605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
